version: '3.8'

services:
  app:
    profiles:
      - dev
    build:
      context: .
      dockerfile: Dockerfile
      # target: development
      # env_file:
      #   - .env
    ports:
      - 3000:3000
    
    depends_on:
      - joia_db
    volumes:
      - ./:/app/.

  joia_db:
    container_name: db
    image: postgres:15

    volumes:
      - joia_db:/var/lib/postgresql/data
      - ./db/docker-volume:/mnt/host

    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: joia

  adminer:
    container_name: joia_adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  joia_db:
